// Genus-level emoji: a real, tight Unicode match for one specific genus,
// not a per-group vibe pick like orderEmoji.ts. Ported from the "Familiar
// Flora" reference artifact, where every entry here was checked against
// data/plants/genera.json (the genus is really in the dataset) and against
// real taxonomic placement -- e.g. Nymphaea (water lily) is deliberately
// absent despite the visual mixup with Nelumbo (true lotus, 🪷), and Piper
// (black pepper) is absent despite the shared English word with Capsicum's
// 🌶️🫑. Most genera have no entry here at all -- that's expected, not a gap
// to fill in.
export const GENUS_EMOJI: Record<string, string> = {
  Acer: "🍁",
  Actinidia: "🥝",
  Allium: "🧄🧅",
  Ananas: "🍍",
  Arachis: "🥜",
  Ariocarpus: "🌵",
  Astrophytum: "🌵",
  Austrocylindropuntia: "🌵",
  Bambusa: "🎋",
  Brassica: "🥬🥦",
  Camellia: "🍵",
  Capsicum: "🌶️🫑",
  Carnegiea: "🌵",
  Castanea: "🌰",
  Cephalocereus: "🌵",
  Cereus: "🌵",
  Citrullus: "🍉",
  Citrus: "🍊🍋",
  Cocos: "🥥",
  Coffea: "☕",
  Consolea: "🌵",
  Coryphantha: "🌵",
  Cucumis: "🥒🍈",
  Cucurbita: "🎃",
  Daucus: "🥕",
  Echinocactus: "🌵",
  Echinocereus: "🌵",
  Epiphyllum: "🌵",
  Ferocactus: "🌵",
  Fragaria: "🍓",
  Glycine: "🫘",
  Gymnocalycium: "🌵",
  Harrisia: "🌵",
  Helianthus: "🌻",
  Humulus: "🍺",
  Hyacinthus: "🪻",
  Ilex: "🧉",
  Ipomoea: "🍠",
  Lactuca: "🥬",
  Lophophora: "🌵",
  Malus: "🍎🍏",
  Mammillaria: "🌵",
  Mangifera: "🥭",
  Melocactus: "🌵",
  Musa: "🍌",
  Nelumbo: "🪷",
  Nicotiana: "🚬",
  Olea: "🫒",
  Opuntia: "🌵",
  Oryza: "🌾🍚🍶",
  Pachycereus: "🌵",
  Pediocactus: "🌵",
  Pelecyphora: "🌵",
  Peniocereus: "🌵",
  Persea: "🥑",
  Phaseolus: "🫘",
  Pilosocereus: "🌵",
  Prunus: "🍒🍑",
  Pyrus: "🍐",
  Rebutia: "🌵",
  Rhipsalis: "🌵",
  Rosa: "🌹",
  Schlumbergera: "🌵",
  Sclerocactus: "🌵",
  Selenicereus: "🌵",
  Solanum: "🍅🥔🍆",
  Spinacia: "🥬",
  Stenocereus: "🌵",
  Theobroma: "🍫",
  Trifolium: "🍀",
  Tulipa: "🌷",
  Vaccinium: "🫐",
  Vanilla: "🍦",
  Vicia: "🫘",
  Vigna: "🫘",
  Vitis: "🍇🍷",
  Zea: "🌽",
  Zingiber: "🫚",
};
